// AUTO-GENERADO por scripts/gen-hg5-importants.ts — NO editar a mano.
// Huellas de las declaraciones !important presentes en el CSS de HG5.
// Regenerar con: npx tsx scripts/gen-hg5-importants.ts (o npm run update-hg5).
export const HG5_IMPORTANT_FINGERPRINTS: string[] = [
  ".btn-label-m:disabled svg-icon,.btn-label-m:disabled svg-icon2,.btn-label-m:disabled md-icon,.btn-label-m[disabled] svg-icon,.btn-label-m[disabled] svg-icon2,.btn-label-m[disabled] md-icon,.btn-label-m.disabled svg-icon,.btn-label-m.disabled svg-icon2,.btn-label-m.disabled md-icon|||background-color|||transparent",
  ".btn-label-m:disabled svg-icon,.btn-label-m:disabled svg-icon2,.btn-label-m:disabled md-icon,.btn-label-m[disabled] svg-icon,.btn-label-m[disabled] svg-icon2,.btn-label-m[disabled] md-icon,.btn-label-m.disabled svg-icon,.btn-label-m.disabled svg-icon2,.btn-label-m.disabled md-icon|||border|||0 solid transparent",
  ".btn-tertiary:disabled svg-icon,.btn-tertiary:disabled svg-icon2,.btn-tertiary:disabled md-icon,.btn-tertiary[disabled] svg-icon,.btn-tertiary[disabled] svg-icon2,.btn-tertiary[disabled] md-icon,.btn-tertiary.disabled svg-icon,.btn-tertiary.disabled svg-icon2,.btn-tertiary.disabled md-icon|||background-color|||transparent",
  ".btn-tertiary:disabled svg-icon,.btn-tertiary:disabled svg-icon2,.btn-tertiary:disabled md-icon,.btn-tertiary[disabled] svg-icon,.btn-tertiary[disabled] svg-icon2,.btn-tertiary[disabled] md-icon,.btn-tertiary.disabled svg-icon,.btn-tertiary.disabled svg-icon2,.btn-tertiary.disabled md-icon|||border|||0 solid transparent",
  ".checkbox-card.is-error .checkbox-card-label|||border|||var(--border-width) var(--border-style) var(--hg-color-error)",
  ".checkbox-card.is-error .checkbox-card-label|||color|||var(--hg-color-error)",
  ".checkbox-radio.is-error label::before|||border-color|||var(--hg-color-error)",
  ".checkbox-radio.is-error span|||color|||var(--hg-color-error)",
  ".is-error .ico-default svg g|||stroke|||var(--hg-color-primary)",
  ".is-error .ico-default svg path|||fill|||var(--hg-color-primary)",
  ".is-error .input,.is-error .help|||color|||var(--hg-color-error)",
  ".is-error svg g|||stroke|||var(--hg-color-error)",
  ".is-error svg path|||fill|||var(--hg-color-error)",
  ".is-error.checkbox-item [type=checkbox]:checked+label::before,.is-error.checkbox-item [type=checkbox]:not(:checked)+label::before,.is-error .checkbox-item [type=checkbox]:checked+label::before,.is-error .checkbox-item [type=checkbox]:not(:checked)+label::before|||border|||var(--border-width) var(--border-style) var(--hg-color-error)",
  ".is-error.checkbox-item a,.is-error .checkbox-item a|||color|||var(--hg-color-error)",
  ".is-error.checkbox-item svg g polyline,.is-error .checkbox-item svg g polyline|||stroke|||var(--hg-color-error)",
  ".is-error.checkbox-item svg g,.is-error .checkbox-item svg g|||fill|||var(--hg-color-error)",
  ".m-0\\!|||margin|||var(--hg-spacing-0)",
  ".mb-0\\!|||margin-bottom|||var(--hg-spacing-0)",
  ".md\\:m-0\\!|||margin|||var(--hg-spacing-0)",
  ".md\\:mb-0\\!|||margin-bottom|||var(--hg-spacing-0)",
  ".md\\:ml-0\\!|||margin-inline-start|||var(--hg-spacing-0)",
  ".md\\:mr-0\\!|||margin-inline-end|||var(--hg-spacing-0)",
  ".md\\:mt-0\\!|||margin-top|||var(--hg-spacing-0)",
  ".md\\:p-0\\!|||padding|||var(--hg-spacing-0)",
  ".md\\:pb-0\\!|||padding-bottom|||var(--hg-spacing-0)",
  ".md\\:pl-0\\!|||padding-inline-start|||var(--hg-spacing-0)",
  ".md\\:pr-0\\!|||padding-inline-end|||var(--hg-spacing-0)",
  ".md\\:pt-0\\!|||padding-top|||var(--hg-spacing-0)",
  ".ml-0\\!|||margin-inline-start|||var(--hg-spacing-0)",
  ".mr-0\\!|||margin-inline-end|||var(--hg-spacing-0)",
  ".mt-0\\!|||margin-top|||var(--hg-spacing-0)",
  ".ok-input .input,.ok-input .help|||color|||var(--hg-color-success)",
  ".p-0\\!|||padding|||var(--hg-spacing-0)",
  ".pb-0\\!|||padding-bottom|||var(--hg-spacing-0)",
  ".pl-0\\!|||padding-inline-start|||var(--hg-spacing-0)",
  ".pr-0\\!|||padding-inline-end|||var(--hg-spacing-0)",
  ".pt-0\\!|||padding-top|||var(--hg-spacing-0)"
]
