// AUTO-GENERADO por scripts/gen-hg5-importants.ts — NO editar a mano.
// Huellas de las declaraciones !important presentes en el CSS de HG5.
// Regenerar con: npx tsx scripts/gen-hg5-importants.ts (o npm run update-hg5).
export const HG5_IMPORTANT_FINGERPRINTS: string[] = [
  ".btn-label-m:disabled svg-icon,.btn-label-m:disabled svg-icon2,.btn-label-m:disabled md-icon,.btn-label-m[disabled] svg-icon,.btn-label-m[disabled] svg-icon2,.btn-label-m[disabled] md-icon,.btn-label-m.disabled svg-icon,.btn-label-m.disabled svg-icon2,.btn-label-m.disabled md-icon|||background-color|||transparent",
  ".btn-label-m:disabled svg-icon,.btn-label-m:disabled svg-icon2,.btn-label-m:disabled md-icon,.btn-label-m[disabled] svg-icon,.btn-label-m[disabled] svg-icon2,.btn-label-m[disabled] md-icon,.btn-label-m.disabled svg-icon,.btn-label-m.disabled svg-icon2,.btn-label-m.disabled md-icon|||border|||0 solid transparent",
  ".btn-primary-feel:disabled svg-icon,.btn-primary-feel:disabled svg-icon2,.btn-primary-feel:disabled md-icon,.btn-primary-feel[disabled] svg-icon,.btn-primary-feel[disabled] svg-icon2,.btn-primary-feel[disabled] md-icon,.btn-primary-feel.disabled svg-icon,.btn-primary-feel.disabled svg-icon2,.btn-primary-feel.disabled md-icon|||background-color|||#a9a9a9",
  ".btn-primary-feel:disabled svg-icon,.btn-primary-feel:disabled svg-icon2,.btn-primary-feel:disabled md-icon,.btn-primary-feel[disabled] svg-icon,.btn-primary-feel[disabled] svg-icon2,.btn-primary-feel[disabled] md-icon,.btn-primary-feel.disabled svg-icon,.btn-primary-feel.disabled svg-icon2,.btn-primary-feel.disabled md-icon|||border|||1px solid #a9a9a9",
  ".btn-quick:disabled svg-icon,.btn-quick:disabled svg-icon2,.btn-quick:disabled md-icon,.btn-quick[disabled] svg-icon,.btn-quick[disabled] svg-icon2,.btn-quick[disabled] md-icon,.btn-quick.disabled svg-icon,.btn-quick.disabled svg-icon2,.btn-quick.disabled md-icon|||background-color|||transparent",
  ".btn-quick:disabled svg-icon,.btn-quick:disabled svg-icon2,.btn-quick:disabled md-icon,.btn-quick[disabled] svg-icon,.btn-quick[disabled] svg-icon2,.btn-quick[disabled] md-icon,.btn-quick.disabled svg-icon,.btn-quick.disabled svg-icon2,.btn-quick.disabled md-icon|||border|||0 solid transparent",
  ".btn-secondary-feel:disabled svg-icon,.btn-secondary-feel:disabled svg-icon2,.btn-secondary-feel:disabled md-icon,.btn-secondary-feel[disabled] svg-icon,.btn-secondary-feel[disabled] svg-icon2,.btn-secondary-feel[disabled] md-icon,.btn-secondary-feel.disabled svg-icon,.btn-secondary-feel.disabled svg-icon2,.btn-secondary-feel.disabled md-icon|||background-color|||#a9a9a9",
  ".btn-secondary-feel:disabled svg-icon,.btn-secondary-feel:disabled svg-icon2,.btn-secondary-feel:disabled md-icon,.btn-secondary-feel[disabled] svg-icon,.btn-secondary-feel[disabled] svg-icon2,.btn-secondary-feel[disabled] md-icon,.btn-secondary-feel.disabled svg-icon,.btn-secondary-feel.disabled svg-icon2,.btn-secondary-feel.disabled md-icon|||border|||1px solid #a9a9a9",
  ".btn-tab:disabled svg-icon,.btn-tab:disabled svg-icon2,.btn-tab:disabled md-icon,.btn-tab[disabled] svg-icon,.btn-tab[disabled] svg-icon2,.btn-tab[disabled] md-icon,.btn-tab.disabled svg-icon,.btn-tab.disabled svg-icon2,.btn-tab.disabled md-icon|||background-color|||transparent",
  ".btn-tab:disabled svg-icon,.btn-tab:disabled svg-icon2,.btn-tab:disabled md-icon,.btn-tab[disabled] svg-icon,.btn-tab[disabled] svg-icon2,.btn-tab[disabled] md-icon,.btn-tab.disabled svg-icon,.btn-tab.disabled svg-icon2,.btn-tab.disabled md-icon|||border|||0 solid transparent",
  ".btn-tertiary:disabled svg-icon,.btn-tertiary:disabled svg-icon2,.btn-tertiary:disabled md-icon,.btn-tertiary[disabled] svg-icon,.btn-tertiary[disabled] svg-icon2,.btn-tertiary[disabled] md-icon,.btn-tertiary.disabled svg-icon,.btn-tertiary.disabled svg-icon2,.btn-tertiary.disabled md-icon|||background-color|||transparent",
  ".btn-tertiary:disabled svg-icon,.btn-tertiary:disabled svg-icon2,.btn-tertiary:disabled md-icon,.btn-tertiary[disabled] svg-icon,.btn-tertiary[disabled] svg-icon2,.btn-tertiary[disabled] md-icon,.btn-tertiary.disabled svg-icon,.btn-tertiary.disabled svg-icon2,.btn-tertiary.disabled md-icon|||border|||0 solid transparent",
  ".checkbox-card.is-error .checkbox-card-label|||border|||1px solid #b40016",
  ".checkbox-card.is-error .checkbox-card-label|||border|||var(--border-width) var(--border-style) var(--hg-color-error)",
  ".checkbox-card.is-error .checkbox-card-label|||color|||#b40016",
  ".checkbox-card.is-error .checkbox-card-label|||color|||var(--hg-color-error)",
  ".checkbox-radio.is-error label::before|||border-color|||var(--hg-color-error)",
  ".checkbox-radio.is-error label::before|||border|||1px solid #b40016",
  ".checkbox-radio.is-error span|||color|||#b40016",
  ".checkbox-radio.is-error span|||color|||var(--hg-color-error)",
  ".formlabel input:-ms-input-placeholder|||color|||#737373",
  ".hidden|||display|||none",
  ".input-line-v2 .input::placeholder|||-webkit-user-modify|||read-only",
  ".is-error .ico-default svg g|||stroke|||#000",
  ".is-error .ico-default svg g|||stroke|||var(--hg-color-primary)",
  ".is-error .ico-default svg path|||fill|||#000",
  ".is-error .ico-default svg path|||fill|||var(--hg-color-primary)",
  ".is-error .input,.is-error .help|||color|||#b40016",
  ".is-error .input,.is-error .help|||color|||var(--hg-color-error)",
  ".is-error svg g|||stroke|||#b40016",
  ".is-error svg g|||stroke|||var(--hg-color-error)",
  ".is-error svg path|||fill|||#b40016",
  ".is-error svg path|||fill|||var(--hg-color-error)",
  ".is-error.checkbox-item [type=checkbox]:checked+label::before,.is-error.checkbox-item [type=checkbox]:not(:checked)+label::before,.is-error .checkbox-item [type=checkbox]:checked+label::before,.is-error .checkbox-item [type=checkbox]:not(:checked)+label::before|||border|||1px solid #b40016",
  ".is-error.checkbox-item [type=checkbox]:checked+label::before,.is-error.checkbox-item [type=checkbox]:not(:checked)+label::before,.is-error .checkbox-item [type=checkbox]:checked+label::before,.is-error .checkbox-item [type=checkbox]:not(:checked)+label::before|||border|||var(--border-width) var(--border-style) var(--hg-color-error)",
  ".is-error.checkbox-item a,.is-error .checkbox-item a|||color|||#b40016",
  ".is-error.checkbox-item a,.is-error .checkbox-item a|||color|||var(--hg-color-error)",
  ".is-error.checkbox-item svg g polyline,.is-error .checkbox-item svg g polyline|||stroke|||#b40016",
  ".is-error.checkbox-item svg g polyline,.is-error .checkbox-item svg g polyline|||stroke|||var(--hg-color-error)",
  ".is-error.checkbox-item svg g,.is-error .checkbox-item svg g|||fill|||#b40016",
  ".is-error.checkbox-item svg g,.is-error .checkbox-item svg g|||fill|||var(--hg-color-error)",
  ".lg\\:hidden|||display|||none",
  ".lg\\:visible|||display|||none",
  ".link-button-prev|||background|||transparent",
  ".m-0\\!|||margin|||var(--hg-spacing-0)",
  ".mb-0\\!|||margin-bottom|||var(--hg-spacing-0)",
  ".md\\:hidden|||display|||none",
  ".md\\:m-0\\!|||margin|||var(--hg-spacing-0)",
  ".md\\:mb-0\\!|||margin-bottom|||var(--hg-spacing-0)",
  ".md\\:ml-0\\!|||margin-inline-start|||var(--hg-spacing-0)",
  ".md\\:mr-0\\!|||margin-inline-end|||var(--hg-spacing-0)",
  ".md\\:mt-0\\!|||margin-top|||var(--hg-spacing-0)",
  ".md\\:p-0\\!|||padding|||var(--hg-spacing-0)",
  ".md\\:pb-0\\!|||padding-bottom|||var(--hg-spacing-0)",
  ".md\\:pl-0\\!|||padding-inline-start|||var(--hg-spacing-0)",
  ".md\\:pr-0\\!|||padding-inline-end|||var(--hg-spacing-0)",
  ".md\\:pt-0\\!|||padding-top|||var(--hg-spacing-0)",
  ".md\\:visible|||display|||none",
  ".ml-0\\!|||margin-inline-start|||var(--hg-spacing-0)",
  ".modalx-fullmobile|||margin|||0",
  ".mr-0\\!|||margin-inline-end|||var(--hg-spacing-0)",
  ".mt-0\\!|||margin-top|||var(--hg-spacing-0)",
  ".ok-input .input,.ok-input .help|||color|||#12882c",
  ".ok-input .input,.ok-input .help|||color|||var(--hg-color-success)",
  ".only-desktop|||display|||none",
  ".p-0\\!|||padding|||var(--hg-spacing-0)",
  ".pb-0\\!|||padding-bottom|||var(--hg-spacing-0)",
  ".pl-0\\!|||padding-inline-start|||var(--hg-spacing-0)",
  ".pr-0\\!|||padding-inline-end|||var(--hg-spacing-0)",
  ".pt-0\\!|||padding-top|||var(--hg-spacing-0)",
  ".sm\\:hidden|||display|||none",
  ".sm\\:visible|||display|||none",
  ".theme-keyboard-accessible *:focus,.theme-keyboard-accessible *:focus-visible,.theme-keyboard-accessible [class*=checkbox-]:focus+label,.theme-keyboard-accessible [class*=checkbox-]:focus-visible+label,.theme-keyboard-accessible [class*=checkbox-] input:focus+label,.theme-keyboard-accessible [class*=checkbox-] input:focus-visible+label|||outline|||2px solid #383bff",
  ".theme-keyboard-accessible .btn-grid .btn:focus,.theme-keyboard-accessible .btn-grid .btn:focus-visible|||outline|||2px solid #383bff",
  ".theme-keyboard-accessible .focus\\:inset:focus,.theme-keyboard-accessible .focus\\:inset:focus-visible|||outline|||2px solid #383bff",
  ".theme-keyboard-accessible .focus\\:outside:focus,.theme-keyboard-accessible .focus\\:outside:focus-visible|||outline|||2px solid #383bff",
  ".theme-keyboard-accessible .md-mini-logo a:focus::before,.theme-keyboard-accessible .md-maxilogo a:focus::before|||outline|||2px solid #383bff",
  ".theme-keyboard-accessible a:focus .product-card-img::before,.theme-keyboard-accessible .product-media__img:focus::before,.theme-keyboard-accessible a:focus .media-image::before|||outline|||2px solid #383bff",
  ".xl\\:hidden|||display|||none",
  ".xl\\:visible|||display|||none",
  "[lang^=zh] *,[lang^=ar] *|||font-family|||helvetica,arial,sans-serif"
]
